### ISSUE TITLE
可以出个线上页面调用的demo么

### ISSUE THREAD

**Issue by fengyikang88** [friendsofhyperf/icomet#1]
只有服务端的代码么？可以出个页面调用服务端的demo么

**Comment by huangdijia** [comment]
可以参考官方 demo：https://github.com/ideawu/icomet-demos

**Comment by fengyikang88** [comment]
那这个怎么引用的方法 引用那个类有demo没

**Comment by huangdijia** [comment]
要仔细看看 demo，后端调 api 注册 token，前端使用 token 跟服务器进行连接。不过建议用 websocket，比较简单写。

**Comment by huangdijia** [comment]
> 那这个怎么引用的方法 引用那个类有demo没

这个只是用 hyperf 框架哦。

**Comment by fengyikang88** [comment]
我知道是这个 我只是想知道你这个调用你这个类里面的方法 是USE 那个。还有那个方法

**Comment by huangdijia** [comment]
> 我知道是这个 我只是想知道你这个调用你这个类里面的方法 是USE 那个。还有那个方法

```php
use FriendsOfHyperf\IComet\ClientInterface;
$client = $container->get(ClientInterface::class);
$client->sign($uid); // ['token' => xxxxx]
```

**Comment by fengyikang88** [comment]
嗯 谢谢
